### PR TITLE
Revert "HACK: scripts: wireguard: Force download from master"

### PR DESCRIPTION
**Pull request by zx2c4**
This is very bad and needs to be reverted.

### CODE REVIEW

**Comment by zx2c4** [comment]
Can you merge this @zipsnet ?

**Comment by Zipsnet** [comment]
Push to gerrit.

**Comment by nathanchance** [comment]
Done: http://gerrit.aicp-rom.com/c/AICP/kernel_google_wahoo/+/68108

**Comment by Zipsnet** [comment]
Thanks, I'm on the go all day. Merged.

**Pull request closed without merging**
